# -*- coding: utf-8 -*-
"""Part C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opD_KMOFDP1PERuQxg2mZ45l0MUsxcQf
"""

from sklearn.model_selection import cross_validate
import time
import pandas as pd

def compare_models(X, y, models_dict):
    results = []

    for name, model in models_dict.items():

        cv_results = cross_validate(
            model, X, y,
            cv=5,
            scoring=['accuracy', 'f1'],
            return_train_score=False
        )

        results.append({
            'Model': name,
            'Acc_Mean': cv_results['test_accuracy'].mean(),
            'Acc_Std': cv_results['test_accuracy'].std(),
            'F1_Mean': cv_results['test_f1'].mean(),
            'F1_Std': cv_results['test_f1'].std(),
            'Fit_Time_Mean': cv_results['fit_time'].mean()
        })

    return pd.DataFrame(results)